### PR TITLE
Version 2.0.0

### LINKED ISSUE #58: Add Java 9 to Travis CI build matrix
Refs #31 and #34

### LINKED ISSUE #101: Mutation testing
Similar to the issue for static analysis, this is the tracking issue for mutation testing:

- [x] [PIT](http://pitest.org)

### LINKED ISSUE #114: Test cases for equals/hashCode implementations
See also:

- [JUnit theory for hashCode/equals contract](https://stackoverflow.com/q/837484/1267663)
- [How should one unit test the hashCode-equals contract?](https://stackoverflow.com/q/188311/1267663)

### LINKED ISSUE #127: Remove 255.255.255.255 from WhoAmI
Refs 7f8efd0743506c820d7d3cf40cd8940e7cbfc087

This seems to be the likely cause of IPv6 issues.

### LINKED ISSUE #133: Update Error Prone to v2.1.2
Refs #131

The newest version of Error Prone, v2.1.2, breaks the build and will need conscious updating.

### LINKED ISSUE #141: Possible read/write races in LamportClock
Using Infer 0.13.0 with [RacerD](http://fbinfer.com/docs/racerd.html):

```
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

FF...........F..................F..F..F.................F.....F.......F.........F..F..............F.........F..F..F....F...F......F.........F.....F....F..F.F....F....F....F............F...F.........F.....F.F............F.............F....F......................F.....F......FF....F.........F...........F....F..............F..........F......F..FF...F....F........F.......F.................F..F......F...F.....F................

Found 4 issues

src/main/java/rxbroadcast/time/LamportClock.java:36: error: THREAD_SAFETY_VIOLATION
  Read/Write race. Non-private method `rxbroadcast.time.LamportClock.time` reads without synchronization from `&this.rxbroadcast.time.LamportClock.time`. Potentially races with writes in methods `{ void LamportClock.set(long),
                                            Object LamportClock.tick(LongFunction) }`.
 Reporting because this access may occur on a background thread.
  34.           lock.lock();
  35.           try {
  36. >             return time;
  37.           } finally {
  38.               lock.unlock();

src/main/java/rxbroadcast/time/LamportClock.java:75: error: THREAD_SAFETY_VIOLATION
  Read/Write race. Non-private method `rxbroadcast.time.LamportClock.toString` reads without synchronization from `&this.rxbroadcast.time.LamportClock.time`. Potentially races with writes in methods `{ void LamportClock.set(long),
                                            Object LamportClock.tick(LongFunction) }`.
 Reporting because another access to the same memory occurs on a background thread, although this access may not.
  73.       @Override
  74.       public final String toString() {
  75. >         return String.format("LamportClock{time=%d}", time);
  76.       }
  77.   

src/main/java/rxbroadcast/time/LamportClock.java:86: error: THREAD_SAFETY_VIOLATION
  Read/Write race. Non-private method `rxbroadcast.time.LamportClock.equals` reads without synchronization from `&this.rxbroadcast.time.LamportClock.time`. Potentially races with writes in methods `{ void LamportClock.set(long),
                                            Object LamportClock.tick(LongFunction) }`.
 Reporting because another access to the same memory occurs on a background thread, although this access may not.
  84.   
  85.           final LamportClock that = (LamportClock) o;
  86. >         return time == that.time;
  87.       }
  88.   

src/main/java/rxbroadcast/time/LamportClock.java:91: error: THREAD_SAFETY_VIOLATION
  Read/Write race. Non-private method `rxbroadcast.time.LamportClock.hashCode` reads without synchronization from `&this.rxbroadcast.time.LamportClock.time`. Potentially races with writes in methods `{ void LamportClock.set(long),
                                            Object LamportClock.tick(LongFunction) }`.
 Reporting because another access to the same memory occurs on a background thread, although this access may not.
  89.       @Override
  90.       public final int hashCode() {
  91. >         return Objects.hash(time);
  92.       }
  93.   }


Summary of the reports

  THREAD_SAFETY_VIOLATION: 4
```

### PR DESCRIPTION
**Pull request by whymarrh**
Refs #87 and #119

🚀

A few more additions to version 2:

- [x] Rename package
- [x] Add JDK 9 to Travis CI build matrix (closes #58)
- [x] Mutation testing (closes #101)
- [x] Test cases for equals/hashCode implementations (closes #114)
- [x] Update Error Prone to v2.1.2 (closes #133)
- [x] Update `WhoAmI` to support IPv6 (closes #127)
- [x] Fix possible races in `LamportClock` (closes #141)

### CODE REVIEW

File: src/main/java/rxbroadcast/VectorTimestamp.java [hunk 1]
```diff
@@ -76,26 +78,30 @@ public boolean equals(final Object o) {
...
-                return this == o;
-            }
-
-            @Override
-            public int hashCode() {
-                return Arrays.hashCode(timestamps);
-            }
-        });
+        if (hashCode == null) {
+            hashCode = Objects.hash(new Object() {
```
Comment (whymarrh) [inline src/main/java/rxbroadcast/VectorTimestamp.java]: This field may need to be calculated in the constructor to be able to automate testing of the equals contract

**Comment by whymarrh** [comment]
The possible races noted in #141 have all been fixed, less one false positive.
